include_guard()

if(NOT DEFINED CMAKE_ANDROID_NDK)
    if(EXISTS $ENV{ANDROID_NDK_HOME})
        set(CMAKE_ANDROID_NDK $ENV{ANDROID_NDK_HOME})
    elseif(EXISTS $ENV{ANDROID_NDK_LATEST_HOME})
        set(CMAKE_ANDROID_NDK $ENV{ANDROID_NDK_LATEST_HOME})
    endif()
endif()

string(REPLACE "\\" "/" CMAKE_ANDROID_NDK ${CMAKE_ANDROID_NDK})
message(STATUS "Using Android NDK: ${CMAKE_ANDROID_NDK}")

set(ANDROID_PLATFORM 26)
set(ANDROID_ABI arm64-v8a)
set(ANDROID_STL c++_static)
set(ANDROID_USE_LEGACY_TOOLCHAIN_FILE OFF)
set(CMAKE_TOOLCHAIN_FILE ${CMAKE_ANDROID_NDK}/build/cmake/android.toolchain.cmake)
